export default {
	SET_OCTAVE: 'SET_OCTAVE',
	SET_DURATION: 'SET_DURATION',
	PLAY_MUSIC: 'PLAY_MUSIC',
	SAVE_MUSIC: 'SAVE_MUSIC',
	SET_CURRENTNOTE: 'SET_CURRENTNOTE',
	ADD_TO_SONG: 'ADD_TO_SONG',
	DELETE_NOTE: 'DELETE_NOTE',
	SET_SELECTED: 'SET_SELECTED',
	SET_SIGN: 'SET_SIGN',
	LOAD_SONG: 'LOAD_SONG',
	SET_SONGID: 'SET_SONGID'
};
